# Generated by Django 5.2.3 on 2025-06-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherforecast',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weather_forecasts', to='mainapp.location'),
            preserve_default=False,
        ),
    ]
